# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOfcm0ILpaCv7WFlsf8oYiSHrihDZNFh

Temperature Analysis
"""

import numpy as np
import time

temps_celsius=np.array([22,25,28,24,26])
temps_fahrenheit=temps_celsius*1.8+32
print("Celsius:",temps_celsius)
print("Fahrenheit:",temps_fahrenheit)
avg_fahrenheit=round(np.mean(temps_fahrenheit),1)
print("Average Fahrenheit:",avg_fahrenheit)

scores=np.array([85,90,78,92,88,76,95,82,89,91,87,84])
print("Shape:",scores.shape)
print("Total elements:",scores.size)
highest=np.max(scores)
lowest=np.min(scores)
print("Highest score:",highest)
print("Lowest score:",lowest)
print("Range:",highest-lowest)

arr_np=np.arange(1,50001)
arr_list=list(range(1,50001))

start=time.time()
sum_np=np.sum(arr_np)
np_time=time.time()-start

start=time.time()
sum_list=sum(arr_list)
list_time=time.time()-start

print("NumPy sum:",sum_np)
print("Python sum:",sum_list)
print("NumPy time: {:.4f} seconds".format(np_time))
print("Python time: {:.4f} seconds".format(list_time))
print("NumPy is {:.1f}x faster".format(list_time/np_time))

